#!/usr/bin/env python3
"""Render the documentation site from the markdown in dims-network/dims.

The docs used to be hand-written HTML here, and they drifted: the "Integration
workflow" page still described developing on a template and propagating
downstream, a process that stopped existing when the monorepo replaced the five
forks. Nobody noticed, because nothing connected a page to the code it
describes.

Now the markdown in the core repository is the source, and these pages are
generated from it at a pinned release -- the same shape as a study's vendored
core. `--check` re-renders and compares, so CI fails if the committed HTML is
not what the pinned release produces.

    python tools/render_docs.py --dims ../dims          # render
    python tools/render_docs.py --dims ../dims --check  # verify, change nothing

Requires `mistune` (see tools/requirements.txt).
"""
from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
OUT_DIR = os.path.join(SITE, "docs")
SOURCE = os.path.join(HERE, "SOURCE.json")

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{title} · DIMS docs</title>
<meta name="description" content="{description}" />
<link rel="stylesheet" href="../style.css" />
<link rel="stylesheet" href="docs.css" />
</head>
<body>

<nav class="nav">
  <div class="wrap nav-in">
    <a class="brand" href="../index.html">DIMS-network</a>
    <div class="nav-links">
      <a href="../index.html">Home</a>
      <a href="../tutorial.html">Tutorial</a>
      <a href="index.html" class="active">Docs</a>
      <a href="https://github.com/dims-network">GitHub ↗</a>
    </div>
  </div>
</nav>

<div class="wrap">
  <div class="docs-layout">
    <aside class="docs-side"></aside>
    <main class="docs-main">

      <div class="crumbs">{group}</div>
{body}
      <p class="source-note">Generated from
        <a href="{source_url}"><code>{source}</code></a>
        at <code>{ref}</code>. Edit it there, not here.</p>

      <footer>
        DIMS-network · <a href="https://github.com/dims-network">github.com/dims-network</a>
      </footer>
    </main>
  </div>
</div>

<script src="docs.js"></script>
{scripts}</body>
</html>
"""

NAV_JS = """/* Renders the docs sidebar from one array and highlights the current page.
   GENERATED by tools/render_docs.py from tools/SOURCE.json -- do not edit.
   The nav and the pages come from one list, so a page cannot go missing from
   the sidebar and the sidebar cannot point at a page that is not built. */
const DOCS_NAV = %(nav)s;

(function renderSidebar() {
  const here = (location.pathname.split("/").pop() || "index.html").toLowerCase();
  const side = document.querySelector(".docs-side");
  if (!side) return;
  side.innerHTML =
    '<div class="docs-side-title">Documentation</div>' +
    DOCS_NAV.map(g =>
      `<div class="docs-group"><div class="docs-group-h">${g.group}</div>` +
      g.items.map(it => {
        const active = it.href.toLowerCase() === here ? ' class="active"' : "";
        return `<a href="${it.href}"${active}>${it.title}</a>`;
      }).join("") +
      `</div>`
    ).join("");
})();
"""


def load_source():
    with open(SOURCE) as fh:
        return json.load(fh)


def link_rewrites(spec):
    """Map a markdown link target in the core onto the page built from it."""
    out = {}
    for group in spec["pages"]:
        for item in group["items"]:
            src = item["source"]
            out[src] = item["out"]
            out[os.path.basename(src)] = item["out"]
            # Contracts link to each other as `contracts/assets.md` and as
            # `../docs/contracts/assets.md`, depending on where they sit.
            out["contracts/" + os.path.basename(src)] = item["out"]
    return out


def render_markdown(text, rewrites, repo_url, ref, source):
    import mistune

    renderer = mistune.HTMLRenderer(escape=False)
    original_link = renderer.link

    def link(text_, url, title=None):
        url = resolve_link(url, rewrites, repo_url, ref, source)
        return original_link(text_, url, title)

    renderer.link = link
    convert = mistune.create_markdown(renderer=renderer,
                                      plugins=["table", "strikethrough", "url"])
    return convert(text)


def resolve_link(url, rewrites, repo_url, ref, source):
    """Point a link at the rendered page, or at the file in the core."""
    if not url or url.startswith(("http://", "https://", "#", "mailto:")):
        return url
    clean = url.split("#")[0]
    anchor = url[len(clean):]

    # The link is relative to the markdown that carried it, so resolve it
    # against that file's directory before anything else. This is what makes
    # `../analyses/crosswavelet.md` in docs/tabs/network.md find the page built
    # from it: matching on the tail alone worked only from docs/ itself, and a
    # link one directory down fell through to a GitHub URL that renders as a
    # working link to the wrong thing.
    target = os.path.normpath(os.path.join(os.path.dirname(source), clean))
    for key in (target, clean.lstrip("./")):
        if key in rewrites:
            return rewrites[key] + anchor

    # Not a page we build (config.schema.json, a source file): send the reader
    # to it in the core, at the pinned ref, rather than to a 404 here. Reading
    # it as repository-relative is what sent `contracts/config.schema.json` in
    # docs/getting-started.md to /blob/<ref>/contracts/..., which does not exist.
    return f"{repo_url}/blob/{ref}/{target.lstrip('/')}" + anchor


def indent(body, spaces=6):
    """Indent the body to sit inside the template, leaving <pre> alone.

    Whitespace is significant inside <pre>, so padding those lines put six
    spaces in front of every line but the first of every code block -- which
    is to say nothing copied out of a docs page pasted as valid shell. The
    line that opens the block is still padded: its spaces sit before <pre>,
    outside the content.
    """
    pad = " " * spaces
    out = []
    in_pre = False
    for line in body.splitlines():
        out.append(line if in_pre else (pad + line if line.strip() else line))
        opens, closes = line.count("<pre"), line.count("</pre>")
        if opens > closes:
            in_pre = True
        elif closes:
            in_pre = False
    return "\n".join(out)


def script_tags(item):
    """The `<script>` tags a page asked for, or nothing at all.

    A page that declares no scripts renders exactly as it did before this
    existed, so adding the mechanism moves no existing byte.
    """
    out = []
    for src in item.get("scripts", []):
        crossorigin = ' crossorigin="anonymous"' if src.startswith("http") else ""
        out.append(f'<script src="{html.escape(src, quote=True)}"{crossorigin}></script>\n')
    return "".join(out)


def copy_assets(dims_root, spec, ref):
    """Files a page needs beside it -- demo data, plotting code -- from the core.

    They live in the core with the markdown that uses them, so a figure and the
    page describing it are released together and `--check` catches either one
    going stale. Only the basename survives the copy, because that is what the
    `<script src>` in SOURCE.json refers to.
    """
    assets = {}
    seen = {}
    for group in spec["pages"]:
        for item in group["items"]:
            for src in item.get("assets", []):
                name = os.path.basename(src)
                if seen.get(name, src) != src:
                    sys.exit(f"error: {src} and {seen[name]} both copy to "
                             f"docs/{name}; give one of them a different name")
                seen[name] = src
                path = os.path.join(dims_root, src)
                if not os.path.exists(path):
                    sys.exit(f"error: {src} is not in {dims_root} at {ref}")
                with open(path) as fh:
                    assets[name] = fh.read()
    return assets


def build(dims_root, spec):
    rewrites = link_rewrites(spec)
    repo_url = spec["repo"].rstrip("/")
    ref = spec["ref"]
    pages = {}

    for group in spec["pages"]:
        for item in group["items"]:
            path = os.path.join(dims_root, item["source"])
            if not os.path.exists(path):
                sys.exit(f"error: {item['source']} is not in {dims_root} at {ref}")
            with open(path) as fh:
                text = fh.read()
            body = render_markdown(text, rewrites, repo_url, ref, item["source"])
            pages[item["out"]] = PAGE.format(
                title=html.escape(item["title"]),
                description=html.escape(item["description"], quote=True),
                group=html.escape(group["group"]),
                body=indent(body),
                scripts=script_tags(item),
                source=html.escape(item["source"]),
                source_url=f"{repo_url}/blob/{ref}/{item['source']}",
                ref=html.escape(ref))

    pages.update(copy_assets(dims_root, spec, ref))

    nav = [{"group": g["group"],
            "items": [{"title": i["title"], "href": i["out"]} for i in g["items"]]}
           for g in spec["pages"]]

    # The landing page is either a page from the core -- a source mapped to
    # index.html -- or, when the manifest names none, the card grid built from
    # the manifest itself. A written index says which reader each page is for,
    # which a grid generated from titles and descriptions cannot; but a grid is
    # better than nothing, so the fallback stays.
    authored_index = any(i["out"] == "index.html"
                         for g in spec["pages"] for i in g["items"])
    if not authored_index:
        nav[0]["items"].insert(0, {"title": "Overview", "href": "index.html"})
    pages["docs.js"] = NAV_JS % {"nav": json.dumps(nav, indent=2)}
    if not authored_index:
        pages["index.html"] = build_index(spec)
    return pages


def build_index(spec):
    cards = []
    for group in spec["pages"]:
        for item in group["items"]:
            cards.append(
                f'        <div class="card web">\n'
                f'          <h3><a href="{item["out"]}">{html.escape(item["title"])}</a></h3>\n'
                f'          <p>{html.escape(item["description"])}</p>\n'
                f'          <div class="links"><a href="{item["out"]}">Read →</a></div>\n'
                f'        </div>')
    body = (
        '      <div class="eyebrow">Documentation</div>\n'
        '      <h1>DIMS documentation</h1>\n'
        '      <p class="lede">Technical reference for the DIMS core, its\n'
        '        self-registering tabs, the Python analyses and the study\n'
        '        repositories that pin them.</p>\n\n'
        '      <div class="callout tip">Every page here is generated from the\n'
        '        markdown in <a href="' + spec["repo"] + '">dims-network/dims</a> at\n'
        '        <code>' + html.escape(spec["ref"]) + '</code>, so it describes the code as\n'
        '        released rather than as remembered. New to DIMS? Start with\n'
        '        <a href="getting-started.html">Getting started</a>.</div>\n\n'
        '      <h2>Sections</h2>\n'
        '      <div class="grid">\n' + "\n".join(cards) + '\n      </div>\n')
    return PAGE.format(title="Documentation", group="Documentation",
                       description="Technical reference for DIMS: architecture, "
                                   "asset layout, the analysis and tab contracts.",
                       body=body, scripts="", source="tools/SOURCE.json",
                       source_url=spec["repo"], ref=html.escape(spec["ref"]))


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dims", required=True, help="path to a dims checkout")
    ap.add_argument("--check", action="store_true",
                    help="compare with what is committed; write nothing")
    args = ap.parse_args()

    spec = load_source()
    pages = build(os.path.abspath(args.dims), spec)

    if args.check:
        stale = []
        for name, content in sorted(pages.items()):
            path = os.path.join(OUT_DIR, name)
            current = open(path).read() if os.path.exists(path) else None
            if current != content:
                stale.append(name)
        if stale:
            print("::error::these pages are not what the pinned core produces: "
                  + ", ".join(stale))
            print("Re-render them: python tools/render_docs.py --dims <checkout>")
            return 1
        print(f"{len(pages)} pages match the core at {spec['ref']}")
        return 0

    os.makedirs(OUT_DIR, exist_ok=True)
    for name, content in sorted(pages.items()):
        with open(os.path.join(OUT_DIR, name), "w") as fh:
            fh.write(content)
        print(f"  wrote docs/{name}")
    print(f"{len(pages)} pages from the core at {spec['ref']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
