#!/usr/bin/env python3
"""Vendor the palette from the core, so this site and the docs cannot disagree.

The colours are defined once, in `docs/stylesheets/dims.css` in
dims-network/dims, where the documentation and the analyses figures read them.
This site used to keep a second copy in the `:root{}` block of style.css. Two
copies of one palette is how a teal stops being the same teal.

So the site vendors it, the same way a study vendors the core: a copy taken from
a pinned release, refreshed by a command, and verified in CI.

    python tools/sync_tokens.py ../dims            # refresh vendor/tokens.css
    python tools/sync_tokens.py ../dims --check     # verify, change nothing

The ref is tools/SOURCE.json, as it is for every other claim this site makes
about a release.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
SOURCE = os.path.join(HERE, "SOURCE.json")
VENDORED = os.path.join(SITE, "vendor", "tokens.css")
IN_CORE = "docs/stylesheets/dims.css"

HEADER = """/* GENERATED by tools/sync_tokens.py -- do not edit.

   The palette, vendored from {repo}
   at {ref}, where it is defined in {path}. Change it there and re-run the
   script; editing this file only makes the site disagree with the docs. */
"""


def tokens_from(css):
    """The first :root{} block -- the tokens, not the Material mapping."""
    start = css.index(":root{")
    depth, i = 0, start
    while i < len(css):
        if css[i] == "{":
            depth += 1
        elif css[i] == "}":
            depth -= 1
            if depth == 0:
                return css[start:i + 1] + "\n"
        i += 1
    raise SystemExit(f"::error::{IN_CORE} has no closed :root block")


def main(dims_root, check=False):
    pin = json.load(open(SOURCE))
    core = os.path.join(dims_root, IN_CORE)
    if not os.path.isfile(core):
        raise SystemExit(f"::error::{core} does not exist. Is {dims_root} a dims checkout?")

    want = HEADER.format(repo=pin["repo"], ref=pin["ref"], path=IN_CORE) + \
        tokens_from(open(core).read())

    have = open(VENDORED).read() if os.path.isfile(VENDORED) else None
    if check:
        if have == want:
            print(f"vendor/tokens.css matches {pin['ref']}")
            return 0
        print("::error::vendor/tokens.css is not what the pinned core defines. "
              "Run: python tools/sync_tokens.py <dims checkout>")
        return 1

    os.makedirs(os.path.dirname(VENDORED), exist_ok=True)
    with open(VENDORED, "w") as fh:
        fh.write(want)
    print(f"{'unchanged' if have == want else 'written'}: vendor/tokens.css ({pin['ref']})")
    return 0


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not args:
        raise SystemExit(__doc__)
    sys.exit(main(args[0], check="--check" in sys.argv))
